Clarify aeso_compiler use
aeternity/aesophia pull request #304
Opened 2021-03-24 10:34 UTC by cytadela8

2021-03-24 12:34 UTC, radrow approved these changes

2021-03-24 15:21 UTC, gorbak25 requested changes
AEVM -> Aeternity Ethereum Virtual Machine

2021-03-25 10:38 UTC, radrow commented
> AEVM -> Aeternity Ethereum Virtual Machine

Why unfold? AEVM is used broadly among our documentation and code

2021-04-29 16:50 UTC, hanssv approved these changes

2021-04-29 16:50 UTC, merged