Add bitwise operations, MULMOD, addr_to_bytes and Poseidon hash
aeternity/aesophia pull request #352
Opened 2021-11-04 09:43 UTC by hanssv

These are extensions to Sophia (and eventually FATE) for the Ceres protocol update. It covers #337 and more.

 This PR is supported by the Æternity Crypto Foundation

2021-11-11 10:54 UTC, UlfNorell requested changes

2021-11-11 10:54 UTC, UlfNorell commented on docs/sophia_syntax.md
> +| `bnot` | right
I would put `bnot` at the same level as `!`. This is what both C and Erlang does.

2021-11-11 20:56 UTC, UlfNorell approved these changes

2021-11-15 11:17 UTC, radrow approved these changes

2021-11-19 10:26 UTC, merged