Add AENS.nameV2/pointeeV2 to introduce raw data pointer
aeternity/aesophia pull request #426
Opened 2022-11-11 15:17 UTC by hanssv

2022-11-12 10:51 UTC, ghallak approved these changes

2022-11-13 21:14 UTC, radrow requested changes

2022-11-13 21:14 UTC, radrow commented on CHANGELOG.md
> +  new pointers.
I don't like mixing incompatible functionalities in the same namespace. Let's create `AENS2` namespace and pack all the new stuff in there.

2022-11-13 21:14 UTC, radrow commented
Btw, shouldn't there be changes in `aeso_fcode_to_fate`?

2022-11-14 07:15 UTC, hanssv commented
I really like the idea of a whole new top-level namespace, I'll test it and see how it turns out.

@radrow there are no changes at the byte code instruction level (yet!) so no changes necessary in `aeso_fcode_to_fate`

2022-11-15 20:21 UTC, hanssv commented
Moved all the active stuff + the new data pointer to `AENSv2` - this turned out nicely I think - good call @radrow !

2022-11-15 21:35 UTC, radrow approved these changes
Looks way better

2022-11-16 20:31 UTC, merged