Add check for number of type variables in type signature
aeternity/aesophia pull request #512
Opened 2024-08-14 09:20 UTC by hanssv

The number of tvars is limited by serialization (u8) to 255 - shouldn't really be an issue for "normal" contracts 😅 

This PR is supported by Æternity Foundation

2024-08-14 10:56 UTC, radrow approved these changes

2024-08-14 15:34 UTC, ghallak requested changes

2024-08-14 15:34 UTC, ghallak commented on CHANGELOG.md
> +- Added a check fo number of type variables in a type signature; it is serialized using 8 bits,
```suggestion
- Added a check for number of type variables in a type signature; it is serialized using 8 bits,
```

2024-08-15 09:29 UTC, ghallak approved these changes

2024-08-26 11:33 UTC, ThomasArts approved these changes

2024-08-26 11:34 UTC, merged